version: "3"
services:
  flask_container:
    build: ./flask-app
    container_name: flask_container
    networks:
      - trio
    ports:
      - target: 5000

  db_container:
    build: ./db
    container_name: db_container
    networks:
      - trio
    ports:
      - target: 3306
    volumes:
      - datavolume:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - trio
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

networks:
  trio: {}
  
volumes:
  datavolume:
