version: "3.8"
services:
  flask_container:
    image: eurosami/flask_container
    build: ./flask-app
    container_name: flask_container
    networks:
      - trio
    ports:
      - '5000:5000'
    environment:
      MYSQL_URI: dfe_db_container
      MYSQL_ROOT_PASSWORD: $MYSQL_PW

  db_container:
    image: mysql:latest
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
      MYSQL_DATABASE: flask-db
    networks:
      - trio
    ports:
      - '3306:3306'
    volumes:
      - dfe_data:/var/lib/mysql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate.sql:ro

  nginx_container:
    image: nginx:latest
    container_name: nginx
    networks:
      - trio
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

networks:
  trio: {}

volumes:
  dfe_data:
