version: "3"
services:
  flask_container:
    build: ./flask-app
    container_name: flask_container
    networks:
      - trio
    ports:
      - target: 5000

  db_container:
    image: mysql:latest
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
      MYSQL_DATABASE: flask-db
    networks:
      - trio
    ports:
      - target: 3306
    volumes:
      - /dfe_data:/var/lib/mysql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate.sql:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - trio
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

networks:
  trio: {}
